### ISSUE TITLE
Remove false entries (actual typos) from spell checking allow lists (OSOE-470)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#103]
For example, just at the beginning of `allow.txt` (https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/spelling/allow.txt) there are multiple such entries: `Driectory`, `Drvier`, `Hidiging`. Further review needed to weed out all of them.

Also remove those unused words that cannot be recognized at first glance.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-470)

**Comment by Piedone** [comment]
I have a hunch these are for typos we don't control and thus can't fix.

**Comment by BenedekFarkas** [comment]
Not at all, these specific examples are in our own code and easy to fix, e.g., being inside a comment or when in code, without breaking anything.

**Comment by Piedone** [comment]
Then strange.

**Comment by porgabi** [comment]
1. Is there a way to see all repositories where GHA is used as a submodule? Just to know which solutions need to be looked at and updated.
2. If this is only concerning allow lists, that means only looking at the `allow.txt` and `expect.txt` files?

**Comment by Piedone** [comment]
1. This most possibly covers OSOCE only, so if you remove an expected typo and fix the typo in the code in one of the submodules there, that should be enough. If you check out the Git history (blame) you'll also see for which issue some expected typo was added, which will hint at where else the typo might be present (if not OSOCE).
2. Yes.

**Comment by BenedekFarkas** [comment]
You can use the GH advanced search to find the occurrences of a given word within the Lombiq organization, e.g., `org:Lombiq Driectory`: https://github.com/search?q=org%3ALombiq+Driectory&type=code

**Comment by porgabi** [comment]
![image](https://user-images.githubusercontent.com/51411356/203092133-1a9a996c-a50d-416d-9b44-f708af2533a9.png)

> Hidiging

![image](https://user-images.githubusercontent.com/51411356/203092391-8ba8c355-c5c5-4bde-8046-b79291e2a84a.png)

**Comment by Piedone** [comment]
Preganante?

**Comment by BenedekFarkas** [comment]
Hidi gang Hidi gang Hidi gang Hidi gang

**Comment by porgabi** [comment]
`Autherization`, `ConfigureMockAutherizationService` — these are found in the Finitive solution. Should I A) only remove them from the allow lists or B) also remove from the Finitive code?

**Comment by BenedekFarkas** [comment]
Fixed in #141
