### ISSUE TITLE
Rename Set-Output script to Set-GitHubOutput (OSOE-473)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#104]
To better communicate what it does ~~and not to trigger the false positive warning from GH:~~

> ~~The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/~~

- [x] Create a copy of `Set-Output` as `Set-GitHubOutput`.
- [x] Add a warning to `Set-Output` stating that it will be removed soon and `Set-GitHubOutput` should be used instead.
- [x] Create a modified version of `Set-GitHubOutput` as `Save-GitHubState` that writes into `$GITHUB_STATE` instead of `$GITHUB_OUTPUT`.
- [x] ~~Then create a PR for it that should be merged as a checkpoint.~~
- [x] Then change the usage of `Set-Output` to `Set-GitHubOutput` in the Lombiq repositories in their own PRs without having to change which branch is referenced from this repo.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-473)

**Comment by Piedone** [comment]
The `Set-Output` script doesn't trigger the warning, that warning came from a different action. So, the question here is whether we'd like to rename or not.

**Comment by BenedekFarkas** [comment]
A more descriptive name would still be useful, even though it's specific to GitHub actions, you might have a bunch of different scripts imported for various purposes.

**Comment by Piedone** [comment]
I'm not arguing with that, just that this issue is purely about the function name, and not related to deprecation warnings.

**Comment by BenedekFarkas** [comment]
OK, so let's do it anyways.

**Comment by BenedekFarkas** [comment]
Fixed in #119
