### ISSUE TITLE
Action pulls latest SQL Server (=2022-latest) but 2019-latest is used (OSOE-481)

### ISSUE THREAD

**Issue by dministro** [Lombiq/GitHub-Actions#116]
The script pulls the `latest` which is `2022-latest` here:

https://github.com/Lombiq/GitHub-Actions/blob/4e7116e87f52c894eb45d4b1758e9fb070445305/.github/actions/setup-sql-server/Initialize-SqlServer.ps1#L15

Then `2019-latest` is used as a parameter for `docker run`.

https://github.com/Lombiq/GitHub-Actions/blob/4e7116e87f52c894eb45d4b1758e9fb070445305/.github/actions/setup-sql-server/Initialize-SqlServer.ps1#L12

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-481)

**Comment by Piedone** [comment]
We should use SQL Server 2022. Also make sure that's installed with Chocolatey too.

**Comment by Psichorex** [comment]
@Piedone To be exact you requested `Also make sure that's installed with Chocolatey too.`.
What I see in the code is that on Windows we are using Chocolatey else we use docker. What exactly did you mean by make sure that SS2022 is installed with Chocolatey?

**Comment by Piedone** [comment]
Just make sure that the same version is installed both under Linux and Windows, where the latter uses Chocolatey (and Linux Docker).
