### ISSUE TITLE
Upgrade check-spelling/check-spelling to latest (OSOE-487)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#127]
This won't be as simple as changing the commit SHA, see: https://github.com/check-spelling/check-spelling/releases/tag/v0.0.21 If, when working on this issue, there's a more recent version, then upgrade to that.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-487)

**Comment by Piedone** [comment]
Are you interested in this, @BenedekFarkas?

**Comment by BenedekFarkas** [comment]
Sure, it's been on my radar for a while! Maybe can start it next week.
