### ISSUE TITLE
Create binlog file during build and add it to build artifacts (OSOE-490)

### ISSUE THREAD

**Issue by 0liver** [Lombiq/GitHub-Actions#132]
This allows to inspect the inner workings of any build, no matter the configured `verbosity`.

Needs this additional parameter on `dotnet build`:

```pswh
-bl:build.binlog
```

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-490)

**Comment by Piedone** [comment]
Are you talking only about the `build-dotnet` action, or the `msbuild˙` one (or both)?

**Comment by 0liver** [comment]
I currently need it for `build-dotnet`, but I could see that it would make sense for both of them.

**Comment by Piedone** [comment]
Let's have this in `build-dotnet` only for now then. If you need this for https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/48 then please go ahead.

**Comment by Piedone** [comment]
Is this something you still need a lot? Because I might be able to take on it. Otherwise, I'll move it down the list of priorities.

**Comment by 0liver** [comment]
It would be very helpful the next time the build fails. I hope it won't, but experience has taught me otherwise. So, yes, if you can, please implement it.
