### ISSUE TITLE
Use per-line spell-checking ignore pattern and remove one-off ignores (OSOE-491)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#134]
With the `check-spelling` action it's possible to mark lines with a custom pattern so they're excluded from spell-checking. See [from this comment](https://github.com/check-spelling/check-spelling/issues/39#issuecomment-1337581186). We should do this instead of adding ignores globally that are only used in a single file (or single instance).

- Use a pattern to ignore single lines. Do this in a way that it'll work in all code files. `#spell-check-ignore-line` is OK for this, since it just needs to be included at the end of the line, but the line can otherwise contain anything. So, e.g. in C#, it can be in a `//` comment. Note that in [this PR](https://github.com/Lombiq/GitHub-Actions/pull/141/files#diff-69b98c817e86a5917f2a134c02be2d39ad8eee4288fc8ee56566dd7a9f844606) the pattern was already configured.
- Go through all the words in _allow.txt_ and _expect.txt_ and if a word is used in <4 places in a single file, then instead ignore lines with the new pattern. (I.e. if there are >3 usages of the word, or it's not just in a single file, then leave the global config.)
- Document this pattern and its usage in _Workflows.md_.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-491)

**Comment by BenedekFarkas** [comment]
Tested this in https://github.com/Lombiq/UI-Testing-Toolbox/commit/175018a19a111ed1838fe001d882f8e39d0b2798 (because of #103), but didn't work ("lombiquitestingtoolbox" occurs only once in the whole solution), then also tried `#no-spell-check-line` (according to https://github.com/check-spelling/check-spelling/wiki/Configuration-Examples%3A-patterns) without success in https://github.com/Lombiq/UI-Testing-Toolbox/commit/e038548ff37d0388ffd6c9139cc143e039779ab0: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/284#issuecomment-1343337087

**Comment by BenedekFarkas** [comment]
Oh, never mind, I thought this pattern is already active from the original action, but instead we need to add it to our own patterns.

**Comment by Piedone** [comment]
Is this still applicable after https://github.com/Lombiq/GitHub-Actions/issues/103 @BenedekFarkas?

**Comment by BenedekFarkas** [comment]
Yep! I added the line ignore pattern (`#spell-check-ignore-line`) towards the end of the original scope of #103 not to produce legacy code, so there are probably a bunch of entries worth sanity-checking. I still added few entries with one or two occurrences that are common enough and it's reasonable to assume that they will appear again, so not all of them are clear cases, but we'll see how this goes.

**Comment by Piedone** [comment]
Got it, thanks.

**Comment by BenedekFarkas** [comment]
Will be done in https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/346 / OSOE-523 instead.
