### ISSUE TITLE
Test and set Ubuntu 22.04 in workflows, and use Windows 2022 only (OSOE-495)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#137]
On the 15th `ubuntu-latest` will refer to Ubuntu 22.04, see [this issue](https://github.com/actions/runner-images/issues/6399). Using this as an occasion, do the following:

- Let's configure all of our workflows to use Ubuntu 22.04 by default (instead of `ubuntu-latest`) and test them.
- Configure all of the Windows defaults/recommendations as `windows-2022`.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-495)

**Comment by sarahelsaig** [comment]
If this is a concern, should we stop using the `*-latest` images in general?

**Comment by Piedone** [comment]
Good idea. Let's actually change this to use the latest OS versions, but hard-coded, so we have control over the upgrades.
