### ISSUE TITLE
Exclude minified files from spell-checking (OSOE-500)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#149]
Spell-checking *.min.js and *.min.css files are useless since those are never edited directly. So, exclude them from the common configuration.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-500)

**Comment by BenedekFarkas** [comment]
I added excludes for those in #141 (https://github.com/Lombiq/GitHub-Actions/pull/141/files#diff-919442c27bcecf956e104417dd7b8484c7f3a15e6ba74f39f10f80ed594514ff). I don't remember exactly, but I think that directly resolved some of the reported spell-checking entries, but I can check the workflow executions before/after the commit.

**Comment by Piedone** [comment]
Ah OK, great then. I've seen this in one of the DotNest repos that now I see actually uses a copy of the config.
