### ISSUE TITLE
Custom spellchecking dictionaries' entries should be sorted by alphabetically (OSOE-502)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#150]
But unfortunately, the order of entries can make a difference in the outcome, so it's not just a simple update, the results need to be carefully checked.
However, alphabetic sorting (mixed casing) is still the best for maintainability (e.g., merging the same entry with different casing, solving merge conflicts).

By @DAud-IcI: In VS Code, select all text, press F1 and start typing "delete duplicate" or "sort lines" respectively.

Maybe even fail the action/workflow (before running the actual spell checking) if the dictionary files aren't sorted correctly?

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-502)

**Comment by sarahelsaig** [comment]
For those who aren't using tools from the late bronze age 😜 
VS Core can do this super easily as well. Select all text, press F1 and start typing "delete duplicate" or "sort lines" respectively

**Comment by BenedekFarkas** [comment]
Oh, lovely, thanks! Updated the issue description.

**Comment by BenedekFarkas** [comment]
@Piedone I wouldn't consider this a good first issue because:

> But unfortunately, the order of entries can make a difference in the outcome, so it's not just a simple update, the results need to be carefully checked.

So, it might be simple to do, but could also lead to some whack-a-mole by having to re-think and consolidate some entries.

**Comment by Piedone** [comment]
Ah OK, removed it, then.
