### ISSUE TITLE
Automatically add #Fixes reference to pull requests based on Jira issue key (OSOE-503)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#151]
Context:
1. When an issue is opened on GitHub, a corresponding Jira issue is created, and the issue's title is suffixed with the Jira issue key. (#52)
2. When a pull request is created on GitHub and the title is prefixed with a Jira issue key, the key is added to the description of the pull request as a link pointing to the actual Jira issue. (#86)

Combining those two, we should also add a #Fixes reference to the pull request if we find a suitable issue ~~on GitHub~~ in the repository, because both the issue and the pull request contains the Jira issue key along specific patterns.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-503)

**Comment by Piedone** [comment]
This should only happen in the same repository. I.e. when a PR is opened and the Jira issue key is added, only GitHub issues in the same repository should be checked.

**Comment by BenedekFarkas** [comment]
I think that's implied, otherwise the reference might be off and the automatic issue resolve (when the PR is merged) won't work but updated the description for clarity.

**Comment by BenedekFarkas** [comment]
Lovely!
