### ISSUE TITLE
Only run add-jira-issue-code-to-pull-request when the PR is opened (OSOE-505)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#152]
Currently, `add-jira-issue-code-to-pull-request` runs when a pull request is opened, and on every subsequent push as well (because `validate-pull-request` and `validate-submodule-pull-request`, where it is executed from, need these triggers). Change this to only run when the PR is freshly opened.

Note that for `validate-pull-request` we use the following triggers:

```
  push:
  pull_request:
    types: [opened, synchronize]
```

Checking on `opened` for this is simple from the `github.event` context. However, `validate-submodule-pull-request` needs to run on every push as well (so it can check for a superproject PR if it wasn't there when the PR was opened), so the only change needed here is to update
https://github.com/Lombiq/GitHub-Actions/blob/20dddc8729dbe1030f734a9e382eb8266e244566/.github/workflows/validate-submodule-pull-request.yml#L24 to `if: github.event.pull_request == opened`

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-505)

**Comment by BenedekFarkas** [comment]
> However, validate-submodule-pull-request needs to run on every push as well (so it can check for a superproject PR if it wasn't there when the PR was opened), so there this check becomes trickier.

I just checked a few submodules in OSOCE and those don't put any restrictions on execution (other than `pull_request`), like OSOCE does. So, wouldn't it be enough to just change https://github.com/Lombiq/GitHub-Actions/blob/20dddc8729dbe1030f734a9e382eb8266e244566/.github/workflows/validate-submodule-pull-request.yml#L24 to `if: github.event.pull_request == opened` (or maybe other triggers too)?

**Comment by Piedone** [comment]
Yes, indeed. The "Ensure Parent PR Exists" needs to run on every push to a PR so its `if` should remain, but yet, for "Add Jira Issue Code to Pull Request" this can simply be what you say.

**Comment by BenedekFarkas** [comment]
OK, cool, I meant that we only change that single line I linked for "Add Jira Issue Code to Pull Request", but "Ensure Parent PR Exists" needs no change.

**Comment by Piedone** [comment]
Yep, I was just clarifying for whoever else reads this.

**Comment by BenedekFarkas** [comment]
Updated description with final instructions.
