### ISSUE TITLE
Authenticate GitHub API request with GITHUB_TOKEN (OSOE-506)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#155]
Anonymous GitHub API requests have a rate limit that we might bump into like [here](https://github.com/Lombiq/Orchard-Base-Theme/actions/runs/3742921659/jobs/6354466657#step:3:23):

![image](https://user-images.githubusercontent.com/1976647/208736492-635980d6-5c8f-4d28-a2d5-52b4a516c343.png)

Look up all GitHub API calls in our scripts and ensure that all of them authenticate with the API using `Get-GitHubApiAuthorizationHeader` (currently this looks like only `Check-Parent`.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-506)

**Comment by sarahelsaig** [comment]
If you use the [GitHub CLI](https://cli.github.com/) app (which is installed by default on all runner images) then your requests are already authenticated. Also it's somewhat neater than using either `curl` or `Invoke-WebRequest`, especially if you have to pass in body parameters. See an example [in this PR](https://github.com/Lombiq/GitHub-Actions/pull/156/files#diff-b946adaf2de629dcdb6507aa8fc44fc36693632765fa86051e2fb5b2d0449ba0). (note that `Get-GitHubApiAuthorizationHeader` is no longer used) Also the GH API documentation has samples for `gh`, but not for `Invoke-WebRequest` so using `gh` would be easier for us.

**Comment by Piedone** [comment]
Oh, very nice. Let's actually use that everywhere. I've opened this issue for that: https://github.com/Lombiq/GitHub-Actions/issues/157 For the immediate bugfix (and easy intro issue) I'm leaving this open in case we can do this first.

**Comment by Piedone** [comment]
I think GitHub changed some API rate limit recently because this starts to become really annoying. So I'm addressing it even though it's really simple :(.
