### ISSUE TITLE
Automate managing issue branch references in workflow files (OSOE-517)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#168]
When you're working on something related to GHA, you'll have to add issue branch references in workflow files when calling reusable workflows or actions, e.g. instead of `@dev` you use `@issue/OSOE-123`. It's painful to have to maintain these: You can forget to add them during development, and you can forget to remove them after a review. So, let's find a better way to do this. Ideally, we wouldn't need to think about managing these references for our own GHA code at all.

- @DAud-IcI mentioned that `validate-pull-request` could check for issue branch references on pushes to the default branch and fail if founds one. While this doesn't solve the management issue, it at least will tell you if you forgot to switch back to `@dev`.
- Automatically managing these would necessitate commits to the repos (including superprojects and submodules). This looks like an issue with submodules.
- A pre-commit Git hook could solve this locally (replace references to ones matching the current branch) but that would need everyone to configure it.
- Handle this in our `checkout` action: If the branch is not the default, replace all `@<default branch>` references with `@<current branch>` in all YML files. This might be a performance impact, we need to check. Also note that while this would cover projects like Lombiq GitHub Actions well (since when you open an issue branch in there, it's correct to point all internal references to that branch), it gets trickier with something like OSOCE: Should the workflows there, that call reusable workflows from LGHA, point to an issue branch? Those will only work if you have a corresponding branch in LGHA, so perhaps not (but handling this only in LGHA may be good enough as a start).
- There doesn't seem to be a built-in way to do this, or a third-party solution.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-517)

**Comment by BenedekFarkas** [comment]
> `validate-pull-request` could check for issue branch references on pushes to the default branch and fail if founds one

I think this is a good compromise in terms of complexity vs. how much it achieves. I'd rather put this in a separate workflow, because you're not really validating the pull request anymore. Although it's important that whoever merged it (or contributed to the PR) is notified in case of a failure, but that's up to personal settings too.

**Comment by Piedone** [comment]
Added some more notes about the `checkout` approach above.

**Comment by davidpuplava** [comment]
PR submitted for this issue. Here are some notes about it.

A new reusable workflow named `validate-gha-refs` was created to search for GitHub Actions workflow and action files and check the references of any "called" workflows. 

There are inputs for what paths to search for GHA files and what files to include. These default to `.github` and `*.yml,*.yaml` respectively.

There is an input for a list of `owner/repository` strings that are used to determine which `uses: owners/repository/...` lines should be considered when checking the version references. By default, it's the repository of the calling workflow. This is useful for the `validate-this-gha-refs` workflow that was added to run the resusable workflow on pushes to the dev branch. One important note here, is that it's possible for a consuming repository to check the version references of any/all called workflows they might be consuming from a different repository.

There is also an input for the expected version to reference by the GHA workflows and actions. By default, this value is the current branch but can be changed to fit the use case scenario.

The `validate-this-gha-refs` currently just runs the GHA Reference check on push to the dev branch, but more can be done here I think. Two use cases come to mind. 

First, is to run this workflow when someone opens a pull request, we can check to make sure the LGHA references are all switched to their issues branch. But, this can be burdensome if they are only modifying a single workflow or action file. Even worse, if they are simply updating a README file and not an action or workflow file. This leads to the second use case.

The second use case is to modify this workflow to further reduce the list of .yml/.yaml files to check, and specifically only check those files that are modified as part of the pull request. If this is solved, then it won't be a burden on the developer to change ALL the version references; they will only need to change the versions of those files they're working on.

Any and all feedback is welcome.

**Comment by Piedone** [comment]
First of all, this works great, good job!

One small remark: the workflow summary is great.

![image](https://github.com/Lombiq/GitHub-Actions/assets/1976647/cb2d61bb-3cc6-4ec9-b132-a6b9c58c1753)

However, please also add a message instructing the person to check it out when a step in the workflow fails, because looking at this was initially confusing:

![image](https://github.com/Lombiq/GitHub-Actions/assets/1976647/3c10c9c9-8e99-48d8-aa02-09271834a797)

Also, please add `Name`s to all jobs and steps.

**Comment by Piedone** [comment]
And in the human-readable strings use "GitHub Actions" instead of "GHA". We know it, but it might not be that obvious for everyone.
