### ISSUE TITLE
Fix formatting of action/workflow files (OSOE-518)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#169]
And include recommendation for editing files (VS Code + https://marketplace.visualstudio.com/items?itemName=me-dutour-mathieu.vscode-github-actions) in the documentation.

Static analysis would also be nice, although this plugin still has false positives, because the underlying language server is not GHA-specific, but the GH team is working on an official one: https://github.com/github/roadmap/issues/564

Maybe https://github.com/oxsecurity/megalinter/blob/main/docs/descriptors/yaml.md?

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-518)

**Comment by 0liver** [comment]
FYI: https://github.com/Lombiq/NodeJs-Extensions/issues/11
