### ISSUE TITLE
Fix publish-nuget only building projects with a solution file (OSOE-521)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#171]
For the issue see e.g.: https://github.com/Lombiq/Orchard-JSON-Editor/actions/runs/3796121799/jobs/6455909410#step:4:1480

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-521)

**Comment by Piedone** [comment]
@0liver please use test with pointing the publish workflow in one of the projects to `@issue/OSOE-521` and let me know if it works for you too.

**Comment by 0liver** [comment]
Hurray! https://github.com/Lombiq/NPM-Targets/actions/runs/3796992999/jobs/6457564256

**Comment by Piedone** [comment]
Great then!
