### ISSUE TITLE
Check Spelling annotations not collapsing (OSOE-525)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#175]
Lately, the PR annotations of Check Spelling are not collapsing after the spelling errors are fixed, see e.g. [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/352#issuecomment-1371515806). These should rather look like this after the errors have been resolved (note "This comment has been minimized.", I opened it):

![image](https://user-images.githubusercontent.com/1976647/210800199-7306645d-4f7a-447a-9868-44a767947622.png)

I suspect this is because of the longer advice configured. If indeed, then we should rather have a short _advice.md_ that links to a longer documentation page.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-525)

**Comment by BenedekFarkas** [comment]
Same thing with the short version that links the one in this repo. Maybe the logic here is that having an advice.md means you want to keep it shown all the time or IDK.

**Comment by Piedone** [comment]
What are you referring to, exactly? The screenshot I've include above uses advice.md but a shorter version, and it properly got collapsed.

**Comment by BenedekFarkas** [comment]
That one! In DotNest Core Sites SDK for example (and at least one more repo I worked on this week), the last failure report wasn't collapsed after an error-free commit. I thought it's just GH having hiccups (it's been behaving strangely in the past week or so), so I collapsed it manually.

**Comment by Piedone** [comment]
In a private repo, you've shown this:

![image](https://user-images.githubusercontent.com/1976647/210862558-b3d278e2-fa0a-4d54-82fc-517564861b50.png)

The difference is that it refers to the comment being **hidden** as opposed to **minimized**. I've checked out older PRs and what seems to be the one that Check Spelling does is the "minimized" one (was the "hidden" one hidden manually?). So, as shown from this, indeed simply the shorter advice doesn't solve this (but having an advice is not a problem, the screenshot in the issue description shows that).

**Comment by Piedone** [comment]
Hmm, [this comment](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/352#issuecomment-1371515806) is properly collapsed (with a long advice, with "minimized") and was added at 11:48 PM CET on 4 January. [This comment](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/352#issuecomment-1372300778) under the same PR isn't, and it was created at 3:37 PM CET on 5 January. Between these only [this commit](https://github.com/Lombiq/GitHub-Actions/commit/34a5bc0d07d2a0266c1c7ffb4e1090f17adbd229) happened but that shouldn't cause it. Also, [this uncollapsed comment](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/349#issuecomment-1370218101) was added on 3 January, so it's not related to some changes we made.

**Comment by Piedone** [comment]
Opened a bug report: https://github.com/check-spelling/check-spelling/issues/44

**Comment by BenedekFarkas** [comment]
That's right, minimized is the automatic, hidden is manual one.

**Comment by Piedone** [comment]
See from https://github.com/check-spelling/check-spelling/issues/44#issuecomment-1372955802. We need to change our implementation according to this.

**Comment by Piedone** [comment]
Fixed in https://github.com/Lombiq/GitHub-Actions/pull/205.
