### ISSUE TITLE
post-pull-request-checks-automation fails with personal access tokens with fine grained access (OSOE-535)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/GitHub-Actions#182]
See the error [in this run](https://github.com/OrchardCMS/OrchardCore.Commerce/actions/runs/3875568764/jobs/6608542530). Looks like the Lombiq repositories use _classic PAT_ because the problem didn't manifest in our repos.

Based on [this comment](https://github.com/cli/cli/issues/6680#issuecomment-1351575528) using the REST resources via the `gh api ...` command should be a workaround. We can test this on [OCC](https://github.com/OrchardCMS/OrchardCore.Commerce/).

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-535)

**Comment by Piedone** [comment]
Yep, the type of the PATs is indeed different between OCC and the Lombiq repos.

**Comment by sarahelsaig** [comment]
Is this something we can change? (I tried looking into it but found nothing.) It would be easier if we could just use classic PAT for OCC.

**Comment by Piedone** [comment]
In principle yes, but it would be better to do the workaround you linked to. Fine-grained PATs are better, and since in the OrchardCMS org we only need this for OCC (and only for one GH API call), it'd be better to keep using that.
