### ISSUE TITLE
In NuGet publish workflow, restrict valid versions to vM.N.O or vM.N.O-alpha.X.[issue-code] (OSOE-536)

### ISSUE THREAD

**Issue by 0liver** [Lombiq/GitHub-Actions#187]
[Jira issue](https://lombiq.atlassian.net/browse/OSOE-536)

**Comment by BenedekFarkas** [comment]
Related: https://github.com/Lombiq/GitHub-Actions/issues/70

This is kind of a duplicate, but not exactly, because generating the version number is (and should be) optional, because this pattern doesn't fit a production release number.

**Comment by 0liver** [comment]
Kind of, yes. But typos in version number keep happening and they sometimes break the upgrade process of freshly versioned packages, because the mistyped version keeps appearing at the top, for example, when actually a newer one exists.

**Comment by 0liver** [comment]
This happened again now: https://github.com/Lombiq/Orchard-Privacy/pull/50/files#diff-0cb3d0d3e8c6b5787f70f48b2d467b21fc55ef86f64fb8a3d13398f414a8271aR54.

I think it would be really easy to add a regex check to the version number for the time being, before someone will tackle and solve the much harder issue #70.

**Comment by adelgeiszt** [comment]
@0liver, if the regex check's result is false, so the version number is incorrect, should the action just simply exit or what's the expected behavior?

**Comment by 0liver** [comment]
It should error out so that the responsible developer can fix the version. Best would be to add the expected format to the error message right away.

**Comment by adelgeiszt** [comment]
Thank you.

**Comment by adelgeiszt** [comment]
@0liver I already tested my code locally, but is it possible to test the workflow with the new condition somewhere?

**Comment by 0liver** [comment]
You can use any of the NuGet-published modules in OSOCE to push new tags out which will generate new versions of a package, e.g. [Node.js Extensions](https://github.com/Lombiq/NodeJs-Extensions). Simply create a new tag at a commit and push that to GitHub.

You'll have to point the repo's publish workflow at this issue's branch, of course.
