### ISSUE TITLE
Add sensible timeouts to all reusable workflows (OSOE-562)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#199]
Our long-running reusable workflows specify [job timeouts](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes), and even surface them as configurable parameters, [like `build-and-test-orchard-core` here](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/build-and-test-orchard-core.yml#L144).

However, we don't have such timeouts configured at all for short-running workflows like `create-jira-issues-for-community-activities`. These will use the default 6-hour timeout.

To prevent excessive resource usage (which can translate into large bills) in case something goes really wrong with such a workflow, do the following for each reusable workflow that doesn't specify the timeout yet:

- Add a configuration parameter for the timeout like we have for some workflows.
- Make these use sensible, comfortable, but as small as suitable default values. Determine this based on the executions of the given workflow [in this repo](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions) and [in OSOCE](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions). E.g. if a workflow usually takes 30s, but you see it hitting 3 minutes here and there, then add a default of 5 minutes. Since we're talking about usually short-running workflows, any nominally small change may be proportionally big, so you can e.g. use the algorithm of "take 150% of the max value I've seen, rounded up to a full minute".

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-562)

**Comment by adelgeiszt** [comment]
There are some workflows that don't specify a timeout yet, such as `post-pull-request-checks-automation`, but there's no execution data for it [here](https://github.com/Lombiq/GitHub-Actions/actions). So what's the issue requirement regarding these workflows?

**Comment by Piedone** [comment]
You'll only find details about runs of those workflows in this repo that actually run for this repo, and `post-pull-request-checks-automation` doesn't. I should've also linked OSOCE, which I updated the issue with now; so for those, check out here: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions

**Comment by adelgeiszt** [comment]
Thank you!
