### ISSUE TITLE
Use "advice" instead of "advices" in .github/actions/spelling/advice.md (OSOE-570)

### ISSUE THREAD

**Issue by DemeSzabolcs** [Lombiq/GitHub-Actions#210]
Advice is an uncountable noun even if the document has multiple entries it's just collectively advice. It is grammatically incorrect to pluralize it except in specific financial and legal documents (see https://en.wiktionary.org/wiki/advice).  Correct it here: https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/spelling/advice.md#spell-checking-configuration-advices:~:text=Spell%20checking%20configuration-,advices,-Basics

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-570)

**Comment by BenedekFarkas** [comment]
Isn't this overkill for a separate issue? Unless you created it for someone specifically to practice contributing to multiple repositories with submodules included.

BTW I'm currently working on https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/346 / OSOE-523, where I'm making changes to every repository involved in spell checking, so I can update them all. We can also add `advices` to the rejected word list.

**Comment by DemeSzabolcs** [comment]
Yeah, it might be overkill. I'm fine with addressing it in OSOE-523.

**Comment by BenedekFarkas** [comment]
Merged into https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/346.
