### ISSUE TITLE
How to skip packing some project (OSOE-574)

### ISSUE THREAD

**Issue by hyzx86** [Lombiq/GitHub-Actions#212]
Hello,

I'm using scripts from this repository  , and it works great.
But I have a problem, when I have some sample projects, how do I set them not to be packaged

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-574)

**Comment by BenedekFarkas** [comment]
Hi! Can you please elaborate on what you don't want packaged? Can you show an example repository?

**Comment by Piedone** [comment]
And which workflow/action are you using from this project?

If it's `publish-nuget`, then note that if there are multiple projects in the repo, then it needs a solution file; it'll try to publish all projects from that. You can remove projects you don't want to publish from that solution (you can specify which solution to use in the workflow, so you can have a separate one), or you can configure `<IsPackable>false</IsPackable>` in the csproj.

**Comment by hyzx86** [comment]
yes ,here  https://github.com/EasyOC/EasyOC.Modules


Originally it also contained a sample Web project, but I set it not to be packaged (I forget the name of that property), and the workflow gave me an error
But today we found that we still need to integrate a Web project to test other modules

> or you can configure `<IsPackable>false</IsPackable>` in the csproj.

That seems to be the choice. Thank you. Let me add it again

**Comment by Piedone** [comment]
Did it fix the issue?

**Comment by hyzx86** [comment]
Hi @Piedone ， It works fine , after when I add `<IsPackable>false</IsPackable>`  in my project file
thank you!

**Comment by 0liver** [comment]
Hi @hyzx86, we're happy that the suggested solution works for you.

For better searchability and trackability of open issues, I would ask you to re-post your question on the version number in a new issue, and close this one since it has been answered with success. This will help other users find answers to their questions faster.

Thank you!

**Comment by hyzx86** [comment]
> Hi @hyzx86, we're happy that the suggested solution works for you.
> 
> For better searchability and trackability of open issues, I would ask you to re-post your question on the version number in a new issue, and close this one since it has been answered with success. This will help other users find answers to their questions faster.
> 
> Thank you!

I'm not sure if this is an Issue with the release script or nuget, I've opened an issue
https://github.com/Lombiq/GitHub-Actions/issues/213
