### ISSUE TITLE
Allow preview release version during NuGet publishing (OSOE-578)

### ISSUE THREAD

**Issue by hyzx86** [Lombiq/GitHub-Actions#213]
Dose the release version number  must be numeric only?

![image](https://user-images.githubusercontent.com/15613121/220831876-4def53c6-93c3-4d9b-9a42-b842189a4056.png)
 
```
Error: "v1.0.9-beta" is invalid. The correct format is "vM.N.O" or "vM.N.O-alpha.X.<issue-code>".
Error: Process completed with exit code 1.
``` 

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-578)

**Comment by 0liver** [comment]
For reference, here's the line of code that's responsible for the check: https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/publish-nuget/action.yml#L65.

Internally, we don't use the `beta` and `preview` suffixes, so we haven't added support for them. For pre-release versions, we use `v1.2.3-alpha.0.OSOE-578` for example. That's what we check against.

I'm not sure whether we are open to add support for other common suffixes, so @Piedone, please chime in.

**Comment by Piedone** [comment]
Yes, patterns like `1.0.0-beta` or `2.0.0-rc.1` are common and should be allowed. @hyzx86, in the meantime, you can reference an earlier commit hash of this repo in your workflow rather than `@dev` to get the old behavior.

**Comment by hyzx86** [comment]
Error: "v1.0.9-alpha.0" is invalid. The correct format is "vM.N.O" or "vM.N.O-alpha.X.<issue-code>".
Error: Process completed with exit code 1.
 
![image](https://user-images.githubusercontent.com/15613121/220865020-86ef163e-e7cf-4eec-99c5-af2f8531d2d0.png)
 
> you can reference an earlier commit hash of this repo in your workflow rather than @dev to get the old behavior.

@Piedone  Sorry, I don't understand what you mean, you mean I copy this script to my repository, right?

**Comment by Piedone** [comment]
By "should be allowed" I mean that we should change this could to allow them, it isn't currently.

Check the workflow that's in your repo that runs the NuGet-publishing reusable workflow from this repo. There should be a `@dev` in there somewhere if you've taken the sample code. Change it to `@f9a7ae562e0e0f75135710a737e6af244cf36a08` and you'll get the old behavior.

**Comment by hyzx86** [comment]
I have  forked  this repo 
https://github.com/EasyOC/GitHub-Actions/blob/7f2db3dbb7478d647d9355945a16c990e97c2742/.github/actions/publish-nuget/action.yml#L63-L69
``` bash
        if ($version -eq 'USE_GITHUB_REF_NAME') {
            $version = $Env:GITHUB_REF_NAME.Trim().TrimStart("v")
            if (!($version -match '^\d+\.\d+\.\d+((-[a-z]{2,}\.\d+)|(\d+-alpha\.\d+\.[a-z]{2,}-\d+))?$'))) {
                Write-Output "::error::`"v$version`" is invalid. The correct format is `"vM.N.O`"  or `"vM.N.O-alpha.X.<issue-code>`" , reg: `"^\d+\.\d+\.\d+((-[a-z]{2,}\.\d+)|(\d+-alpha\.\d+\.[a-z]{2,}-\d+))?$`"  ."
                exit 1
            }
        }
```

And then update my workflow like this:

https://github.com/EasyOC/EasyOC.Modules/blob/ad2e768459f9992f8de4c0b042b205e3e978280f/.github/workflows/publish_to_nuget.yml#L8-L12
``` bash
name: Publish to NuGet
on:
  push:
    tags:
      - v*

jobs:
  publish-nuget:
  #https://github.com/Lombiq/GitHub-Actions/blob/dev/Docs/Workflows.md#nuget-publish-workflow
    uses: EasyOC/GitHub-Actions/.github/workflows/publish-nuget.yml@version_rule
    secrets:
      API_KEY: ${{ secrets.NUGET_API_KEY }}
```



But when I published it looked like it was still running the old script.

![image](https://user-images.githubusercontent.com/15613121/220927770-ce60e287-3f43-47df-ad74-7a20ee0f4db1.png)

**Comment by Piedone** [comment]
You need to change it here: https://github.com/EasyOC/GitHub-Actions/blob/7f2db3dbb7478d647d9355945a16c990e97c2742/.github/workflows/publish-nuget.yml#L87

**Comment by hyzx86** [comment]
> You need to change it here: https://github.com/EasyOC/GitHub-Actions/blob/7f2db3dbb7478d647d9355945a16c990e97c2742/.github/workflows/publish-nuget.yml#L87

Done ,Thanks !

**Comment by Piedone** [comment]
Great then!

While your question is answered here, let's keep the issue open to allow preview versions.
