### ISSUE TITLE
Breaking API change detector during NuGet publishing (OSOE-597)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#220]
In the `publish-nuget` action, let's add a feature to detect breaking changes compared to the previous released version, and fail the build if the version number doesn't reflect the breaking change.

- The [package validator](https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/baseline-version-validator) feature can be used for this.
- Following [Semantic Versioning](https://semver.org/), only major version increases (e.g. v2.0.0 after v1.2.3) may contain breaking changes. The build should thus fail if the version increase is minor or patch, but a breaking change is detected.
- The baseline version to compare against should be the previous latest released (i.e. not alpha/beta or other prerelease) version of the same lineage. E.g. if v1.2.3 is released it should be compared against v1.2.2 (or any v1.2.x that exists, or if no such exists then v1.x.x), v1.3.0 should be compared against the previous v1.x.x.
- If the major version changes, then no validation should be done since breaking changes are allowed.
- Prerelease versions shouldn't be checked.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-597)

**Comment by 0liver** [comment]
If we're going to set all this up, it might make sense to inform us developers of breaking changes already during development.

So, let's also check pre-release versions and add a warning to inform about the necessity to use a new major version for the release. Much like the spell checker generates a panel with information about its execution.

**Comment by Piedone** [comment]
I worked on this already and didn't do this deliberately: https://github.com/Lombiq/GitHub-Actions/issues/45#issuecomment-1240568296
