### ISSUE TITLE
Remove boilerplate in the form of input parameter properties which use default values (OSOE-614)

### ISSUE THREAD

**Issue by 0liver** [Lombiq/GitHub-Actions#227]
Many of our workflow files have grown over 100 lines long, and a big part in that play the input parameter definitions.

Most of them use the default properties `type: string` and `required: false`, which could simply be omitted. Here's an example:

```diff
diff --git a/.github/workflows/build-and-test-orchard-core.yml b/.github/workflows/build-and-test-orchard-core.yml
index b65cdf77..8ad12038 100644
--- a/.github/workflows/build-and-test-orchard-core.yml
+++ b/.github/workflows/build-and-test-orchard-core.yml
@@ -30,26 +30,18 @@ on:
         default: 6.0.x
         description: Version of the .NET SDK to set up.
       blame-hang-timeout:
-        required: false
-        type: string
-        default: ""
+        default: ''
         description: >
           Run the tests in blame mode and collects a hang dump when a test exceeds the given timeout. See
           https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test for details on available values.
       build-directory:
-        required: false
-        type: string
         default: .
         description: Path to the directory where a solution file can be found.
       build-configuration:
-        required: false
-        type: string
         default: Release
         description: Configuration parameter for dotnet build (e.g. Debug, Release).
       build-solution-path:
-        required: false
-        type: string
-        default: "*.sln"
+        default: '*.sln'
         description: >
           The path of the solution or project file to be built. If there's exactly one .sln file in the build directory
           then this can be omitted. For further information, see the documentation of the build-dotnet action.
```

With the usage of GitHub Actions growing, I think we're at a point where these default can be omitted in code.

One other point, that could make sense as part of touching all of our workflow files, would be replacing the wider `"` characters for the leaner `'` apostrophe, as shown in the above diff.

What do you think?

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-614)

**Comment by Piedone** [comment]
I'm all for brevity if it doesn't hurt readability, though I'm not sure here, since these are public configuration parameters. I.e., anybody consuming these workflows/actions should be able to understand the parameters. If these defaults are well-known among GHA developers then sure (I personally didn't know about these until now, but that's not representative).

The apostrophe thing is something we actually changed in the other direction a while ago :D. But using a single quote is perhaps better, because job conditions (`if`s) downright require them when checking for strings, double quotes silently won't work.

**Comment by Psichorex** [comment]
Just to be clear here @TheHydes as you work on this `type` is actually required and will produce error if it is removed.

**Comment by Piedone** [comment]
Reopening since this is still in progress. Please reference this issue from the new PR too.
