### ISSUE TITLE
Create Jira issues for community activities doesn't work for external pull requests (OSOE-676)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#251]
If an external contributor opens a pull request from their fork, the "Create Jira issues for community activities", just as all other workflows, will [need approval to run](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks). So, we won't get notified about somebody opening a pull request until somebody notices the pull request and approves the runs, [like this](https://github.com/Lombiq/Lombiq-Orchard-Visual-Studio-Extension/pull/32):

![image](https://github.com/Lombiq/GitHub-Actions/assets/1976647/e76e9b61-a0c1-437d-8d0d-7d66cd47e7fe)

Even if the workflow is approved to run, it'll fail because it won't be able to access organization secrets:

![image](https://github.com/Lombiq/GitHub-Actions/assets/1976647/90413c82-a2f0-48ad-bd62-464e8fab2e86)

This is not an issue for issues and discussions.

Figure out a way around this. Can't we somehow run the workflow outside the context of the PR?

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-676)

**Comment by wAsnk** [comment]
I found the easiest way to do this would be a scheduled job that would run every day or 12 hours. What do you think @Piedone ?

**Comment by Piedone** [comment]
That'd be certainly a way, yes, but these [are eventually disabled for less active repos](https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow):

> Warning: To prevent unnecessary workflow runs, scheduled workflows may be disabled automatically. When a public repository is forked, scheduled workflows are disabled by default. In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days.

Some of our repos in question would certainly be affected.

**Comment by wAsnk** [comment]
Then the next option would be to create a webhook service tenant e.g. in Lombiq Tenants that would check these PRs through a GitHub webhook and make a REST API call to GitHub and trigger the "Create Jira issues for community activities" GitHub Action. Or simply a scheduled REST API call to trigger this action, then the webhook is not needed.

**Comment by Piedone** [comment]
Yeah, that would work. Have a private repo just for this, that triggers the workflow for all affected OSS repos of ours, like once every day. There, I'd have a single script that triggers all such repos (so not like we need a separate workflow for each repo, all can be in one).

Need to document what one needs to do there when initializing a new repo.

**Comment by wAsnk** [comment]
> Yeah, that would work. Have a private repo just for this, that triggers the workflow for all affected OSS repos of ours, like once every day. 

That's not exactly what I was thinking, but that might be even better. Let's go with that then. Could you create this new private repo then, please? I will start the work there. The repo name could be GitHub-Jira-Sync e.g.

**Comment by Piedone** [comment]
I found a better option; my original message I started to write is below for some tips for the webhook approach, should it still become useful.

Instead of the `pull_request` trigger we should use the `pull_request_target` one, [see the docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories):

>Note: Workflows triggered by pull_request_target events are run in the context of the base branch. Since the base branch is considered trusted, workflows triggered by these events will always run, regardless of approval settings. For more information about the pull_request_target event, see "[Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)."

This sounds exactly what we need, but please test (you need to do this with a fork PR for a repo where that user doesn't have write access).

So, I think what we need to do:

- Update all affected repos of ours, including the open-source template repo and OCC. 
- Update the docs in this repo.
- Check all of our active open-source repositories for PRs we missed.

---

Ah, I misread. I thought you wanted to have this in the Lombiq Tenants repo; didn't understand as it being OC code. But doing this in an OC workflow seems easier, also because the `LOMBIQBOT_GITHUB_PERSONAL_ACCESS_TOKEN` organization secret can be used as the personal access token for the trigger requests.

Note that this will need changing all workflows in all affected repos to include the webhook trigger too, and also docs how someone can implement the same thing in their repos.

BTW simply triggering "Create Jira issues for community activities" via a webhook will not be enough, since you need to somehow run the code only for newly opened repos.

**Comment by wAsnk** [comment]
By the description of the activity I thought that running it would create all missing issues for all new PRs: "Creates Jira issues for community activities happening on GitHub, like issues, discussions, and pull requests being opened. Pull requests are only taken into account if they're not already related to a Jira issue (by starting their title with a Jira issue key)." 

So this isn't the case?

**Comment by Piedone** [comment]
Perhaps, but it doesn't really matter with the different trigger I mentioned.
