### ISSUE TITLE
update-github-issue-and-pull-request action shouldn't fail when issues are disabled (OSOE-689)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#256]
When the Issues feature is disabled on the repository, update-github-issue-and-pull-request fails instead of skipping the issue check.

> the 'Lombiq/XYZ' repository has disabled issues
No issue was found with the query 'ASDF-123 in:title' in the repository 'Lombiq/XYZ'

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-689)

**Comment by Psichorex** [comment]
@BenedekFarkas Could you give me an example of a repository where the issues feature is disabled?
Update: I see that some private repos have this disabled.

**Comment by Psichorex** [comment]
@BenedekFarkas Do I see it correctly that the action is not directly failing so it does not produce a complete action fail but just returns this error message ? I checked repos where this is the case and the action and the job was kind of passing eventhough this error message `No issue was found with the query 'ASDF-123 in:title' in the repository 'Lombiq/XYZ'` was present. If there was a completely failing job that you noticed, could you maybe send a link of that run?

**Comment by BenedekFarkas** [comment]
Nope, the job failed due to this error. I'll follow-up in Jira about it, because it's a private project.

**Comment by Piedone** [comment]
The implementation under https://github.com/Lombiq/GitHub-Actions/pull/258/ prevents the update of the PR with the Jira issue key too when GitHub issues are disabled. This is not suitable, since we definitely use Jira issues when not using GitHub issues.

**Comment by BenedekFarkas** [comment]
Indeed. The relevant part of [Update-GitHubIssueAndPullRequest](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/update-github-issue-and-pull-request/Update-GitHubIssueAndPullRequest.ps1), where the original error came from:

```
$issueQuery = "$issueKey in:title"
$output = gh issue list --search $issueQuery --repo $GitHubRepository
$issueItem = ($output | Select-Object -First 1)

if ($issueItem)
{
    // Logic to update the issue.
}
```

So the check against having issues happens too high in the code hierarchy now (in [validate-pull-request](https://github.com/Lombiq/GitHub-Actions/pull/258/files#diff-523b16b390ec130c7848d1c2cb92b7c7d57faf5242301f2c9f4a2b022eefde6aR30) and [validate-submodule-pull-request](https://github.com/Lombiq/GitHub-Actions/pull/258/files#diff-6acad7caf6c5510ba72f65789983c329111d11967bcce3973f2e7b6241e340edR34)), instead just Update-GitHubIssueAndPullRequest should be changed like this:
```
$issueQuery = "$issueKey in:title"
$issueItem = $null
if ((gh api repos/$GitHubRepository | ConvertFrom-Json).has_issues)
{
    $output = gh issue list --search $issueQuery --repo $GitHubRepository
    $issueItem = ($output | Select-Object -First 1)
}
```

**Comment by BenedekFarkas** [comment]
This is more to the point (slightly more code, but only fetches the information we need):
```
(gh repo view $GitHubRepository --json hasIssuesEnabled | ConvertFrom-Json).hasIssuesEnabled
```

**Comment by Piedone** [comment]
What's more, the `if: github.event_name == 'pull_request' && github.event.action == 'opened' && steps.check-issues-are-enabled.outputs.issues-enabled == 'false'` condition in `validate-submodule-pull-request` also disables the "Update GitHub issue and Pull Request" step when issues are actually enabled.

I'm reverting the https://github.com/Lombiq/GitHub-Actions/pull/258 PR in `dev`.

**Comment by Psichorex** [comment]
@Piedone 


> What's more, the `if: github.event_name == 'pull_request' && github.event.action == 'opened' && steps.check-issues-are-enabled.outputs.issues-enabled == 'false'` condition in `validate-submodule-pull-request` also disables the "Update GitHub issue and Pull Request" step when issues are actually enabled.
> 
> I'm reverting the #258 PR in `dev`.

Yes that is logical as the if statement was supposed to check for "true" so that was a OOPSIE left behind `== false` there.
