### ISSUE TITLE
Migrate away from deprecated gajira* actions (OSOE-722)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#275]
We use Atlassian's own gajira* actions (like https://github.com/atlassian/gajira-login and https://github.com/atlassian/gajira-create) to interact with Jira. However, these are deprecated and there's no official guidance on what to use instead of them (see https://github.com/atlassian/gajira/issues/18). They also use the now deprecated v16 of Node.js. So, we should figure out what to use instead.

Most possibly we can interact with the Jira RESTful API directly from PowerShell, or perhaps there's some PS module to make this easier too. We can also check out https://github.com/ankitpokhrel/jira-cli.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-722)

**Comment by BenedekFarkas** [comment]
We can try maintaining (fork) them and or even take over stewardship of these (both have a few dozen stars, so we could put our name in front of a new audience) unless it's significantly harder than just calling the API, but I guess a breaking change would affect both kinds of tools the same way.

**Comment by Piedone** [comment]
Yeah, that would be an option as well.

**Comment by Piedone** [comment]
For now, what needs to be done to keep these actions working in the mid-term, is updating their Node.js version from 16 to 20. They'll use v20 in any case from some time next spring (see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), at which point they might break.

**Comment by Piedone** [comment]
We need better restrictions for such API access, so instead, we should do https://github.com/Lombiq/GitHub-Actions/issues/277.

**Comment by Piedone** [comment]
This is again needed, see https://github.com/Lombiq/GitHub-Actions/issues/277#issuecomment-1937188231

**Comment by Piedone** [comment]
Looked into using https://github.com/AtlassianPS/JiraPS. However, the latest release of it is from 4 years ago (even though there are recent updates in the repo), not much activity in the issue tracker, and we'd need to work around it not having a feature to add remote links: https://github.com/AtlassianPS/JiraPS/issues/375.

Looked into https://github.com/ankitpokhrel/jira-cli too. That looks great, but seems more of an interactive CLI than something suited for unattended scripts. Installing it would be uneasy too.

So, we'll go with vanilla PS for now.
