### ISSUE TITLE
Prevent Azure-related workflows running at the same time when interacting with the same environment(s) (OSOE-729)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#281]
For example, running `deploy-to-azure-app-service` and `reset-azure-environment` against the same environment will cause them to step on each other's toes (and fail or do something unexpected), same goes for any of these two and `swap-azure-web-app-slots` (also fix the O1 variants).

Update the [concurrency](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) group names to be dynamic by using the slot name parameters.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-729)

**Comment by Piedone** [comment]
I swear we've done this in our own workflows before but it's not there now.

BTW what needs to be used for this is [`concurrency`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency), with a key that reflects the environment.

**Comment by BenedekFarkas** [comment]
We already have concurrency, added in #221, but the good news is that my comment there stating that

> Only the github context is available here, so we can't make it dynamic based on the parameters (such as the app slot name) passed to the workflow.

is no longer true!

**Comment by Piedone** [comment]
Ah, it wasn't in our own workflows. So to be clear, we have concurrency prevention in place with a const key, thus this issue is only interesting if you run these workflows with multiple environments, right?

E.g, if you have a single staging environment for a given app that you want to run the reset workflow for, then you're all set. However, if you have a staging and dev environments (accessed by the same GitHub repo) then the current setup prevents you from running a reset for both at the same time.

So, what we have currently is adequate for single environments, and suboptimal but safe for multiple ones.

**Comment by BenedekFarkas** [comment]
No. The current solution prevents running multiple instances of the same workflow, even if they target different environments (which is suboptimal, but not a problem for us). The real problem is what's in the opening message: Running both `deploy-to-azure-app-service` and `reset-azure-environment` against the Staging environment at the same time for example.

Previously with TeamCity we were using [shared resources](https://www.jetbrains.com/help/teamcity/shared-resources.html), which (in the case of  `deploy-to-azure-app-service` and `reset-azure-environment`) would prevent this by putting a write lock on the Staging environment (the resource name was something like `Azure_App_Slot_Staging`) and a read lock on Production. Swap had a write lock on both.

With how concurrency groups worked previously in GHA, we couldn't do this (since it couldn't be aware of the slot parameters), so I added the maximum restriction possible (preventing running multiple instances of the same workflow), but now we should be able to do something similar as the earlier TC configuration. We'll need to check if a given workflow can be in multiple concurrency groups (the documentation doesn't say anything about that).

**Comment by Piedone** [comment]
I see, because they use different concurrency groups.

**Comment by Piedone** [comment]
As a quick fix, we could just use the same concurrency group in all of these workflows (including swap too), no?

**Comment by BenedekFarkas** [comment]
Almost, but we no longer need to make that compromise, since now we can set the concurrency group of both `deploy-to-azure-app-service` and `reset-azure-environment` to something like `WriteAzureApp${{ inputs.destination-slot-name }}Slot`.

~But the caller swap workflow is usually in a different repo, so we can't prevent it from running at the same time as the others using concurrency groups.~

Edit: I just realized we need to include the app name too, because the concurrency groups affect the whole organization.

**Comment by BenedekFarkas** [comment]
Concurrency group can only be a single string, so the best compromise looks like to use the app name, e.g., `${{ inputs.app-name }}AzureWorkflow`. That way only one of the Azure-related workflows can run at a given time for an app (which is still overly restrictive if you have more than two slots, but it's OK for us for now).

Edit: It only works within a repository, so with the swap workflows usually being a separate repo, we can't prevent them from starting when e.g., Deploy is running, but we still prevent it from running multiple instances at the same time (like before).
