### ISSUE TITLE
Add wrapper for the markdownlint-cli2 action (OSOE-744)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#289]
[markdownlint-cli2](https://github.com/DavidAnson/markdownlint-cli2-action) looks like the shortest path to standalone Markdown linting that doesn't rely on [Lombiq.NodeJs.Extensions](https://github.com/Lombiq/NodeJs-Extensions) (which needs a solution to be built in).

The action is developed by the author of the [markdownlint](https://github.com/DavidAnson/markdownlint) library, which is what Lombiq.NodeJs.Extensions uses as well.

Useful for documentation-heavy repositories, such as this one, so we don't have to wait for the OSOCE build to surface MD linting errors, similarly how this repository has its own spell checking.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-744)

**Comment by Piedone** [comment]
We don't need a separate issue for this, https://github.com/Lombiq/NodeJs-Extensions/issues/11 covers this (that's also about having something outside of NE, it was only opened there because we initially thought it's most applicable to be done in NE). Please add this info there.

**Comment by BenedekFarkas** [comment]
I see no mention of markdown there and Lombiq.NodeJs.Extensions already does MD linting. The wrapper (and the issue) belongs in this repo, that's exactly the point of this issue (not having to use Lombiq.NodeJs.Extensions).

**Comment by Piedone** [comment]
Ah sorry, I was in the YML mindset. Yes, this is unrelated to https://github.com/Lombiq/NodeJs-Extensions/issues/11 and valid here.
