### ISSUE TITLE
Hidden, but syntactically incorrect links inserted to issue and PR descriptions (OSOE-750)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#294]
I noticed this under multiple PRs of my own issue and found other cases too: Something that resembles a regular issue link in MD format is inserted into PR descriptions (even if it already has a correct issue link), but it's not a complete link and isn't rendered. Might be down to a breaking change by Atlassian when supplying the link to an issue through the issue API.
We should also get rid of the tracking query string.

Example description source:

```
[OSOE-743](https://lombiq.atlassian.net/browse/OSOE-743)

[OSOE-743]: https://lombiq.atlassian.net/browse/OSOE-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
```

Example PRs:
- https://github.com/Lombiq/Infrastructure-Scripts/pull/33
- https://github.com/Lombiq/PowerShell-Analyzers/pull/36
- https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/636
- https://github.com/Lombiq/GitHub-Actions/pull/292
- https://github.com/Lombiq/GitHub-Actions/pull/293

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-750)

**Comment by Piedone** [comment]
I think this is rather some strange bug in the GH editor. The hidden links might at one point be added by our workflows, but at least they're re-added by GH without any workflows running:

https://github.com/Lombiq/GitHub-Actions/assets/1976647/e2859a55-a537-4185-8730-f55cd4212b49

Or, perhaps they're added by GH for some reason to begin with. Maybe some clash between the explicitly added `[OSOE-743](https://lombiq.atlassian.net/browse/OSOE-743)` link and [autolinks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls).

[OSOE-743]: https://lombiq.atlassian.net/browse/OSOE-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by BenedekFarkas** [comment]
I was going to send in a very detailed description of what I tried, but all of that was a red herring, it was Jira all along!
Related issues:
- https://github.com/atlassian/github-for-jira/issues/1820
- https://github.com/atlassian/github-for-jira/issues/1858
- https://github.com/atlassian/github-for-jira/issues/2046
