### ISSUE TITLE
Publishing NuGet packages doesn't work with centralized package management (OSOE-832)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/GitHub-Actions#339]
Package generation fails for both CloudSmith and NuGet on OrchardCore.Commerce. [Here](https://github.com/OrchardCMS/OrchardCore.Commerce/actions/runs/8403448570/job/23013939199) is an example.

> /home/runner/work/OrchardCore.Commerce/OrchardCore.Commerce/src/Modules/OrchardCore.Commerce.ContentFields/OrchardCore.Commerce.ContentFields.csproj : *error NU1008*: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: *Microsoft.SourceLink.GitHub*. [/home/runner/work/OrchardCore.Commerce/OrchardCore.Commerce/OrchardCore.Commerce.sln]

The Microsoft.SourceLink.GitHub package reference is added in [Add-SourceLinkPackage.ps1](https://github.com/Lombiq/GitHub-Actions/blob/6932e265c4d1b1809934194ba691a112b3fb2367/.github/actions/publish-nuget/Add-SourceLinkPackage.ps1#L14). The script should try to detect if _Directory.Packages.props_ exists and act accordingly.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-832)

**Comment by Piedone** [comment]
If you need this for OCC then please work on it.

**Comment by Piedone** [comment]
A few thoughts on approaching this:

- The obvious solution is to detect centralized package management and add the package reference to the props file (though I'm not sure that's a generic enough solution) as well as a reference different than the default one to the project files.
- Maybe somehow adding SourceLink can be forced still? (That would be acceptable to me, unlike doing such an override in the actual codebase.) Perhaps, but I don't think so. See https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management#overriding-package-versions
- Add SourceLink to OCC by hand, and detect it existing here?

**Comment by sarahelsaig** [comment]
I feel like I'm missing something obvious here. Why are we pre-fetching the package version and  manually editing the XML instead of using the `dotnet` CLI, [like this](https://github.com/Lombiq/GitHub-Actions/commit/cac4291b64e10913f052a5cffd82a4e620a26bea).
```pwsh
dotnet add $projectFile.FullName package 'Microsoft.SourceLink.GitHub' --source 'https://api.nuget.org/v3/index.json'
```
Seems way simpler and more future-proof to me (and yes, it works with _Directory.Packages.props_ out of the box).

**Comment by Piedone** [comment]
This looks like a much better solution indeed.
