### ISSUE TITLE
Fix build-and-test-orchard-core workflow fails to upload failure dumps under Windows, if the app contains a file with a long path (OSOE-851)

### ISSUE THREAD

**Issue by DemeSzabolcs** [Lombiq/GitHub-Actions#347]
This is a Windows specific issue. I suspect that this is because of the Windows max path length which is ~256 characters.

Example log:
```
Total tests: 1
     Failed: 1
 Total time: 2.0352 Minutes
Test Run Failed.
Test failed: test\Example-Project.Tests.UI\Example-Project.Tests.UI.csproj
Error: Process completed with exit code 1.
Run Merge-FailureDumps -Directory "."

    Directory: C:\a\Example-Project\Example-Project

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           5/11/2024  5:50 PM                FailureDumps

Run actions/upload-artifact@v3.1.1
Error: ENOENT: no such file or directory, realpath 'C:\a\Example-Project\Example-Project\FailureDumps\Example_Project_Tests_UI_Tests_ExamplePage_VisualVerificationTests_VisualVerificationTests_VerifyTheTestPage\Attempt 0\AppDump\Recipes\media\ExampleSite\VehiclePages\GroundVehicles\Cars\BMW\BMW Individual M760Li xDrive Model V12 Excellence`
```

In this example, there is a folder that contains images inside the `Recipes` folder. These are always added to the failure dumps. However this path is too long for Windows (it's over ~256 character). In this case nothing happens, nothing is uploaded. So there is no failure dump on GitHub.

Expected behavior: There should be a workaround, to get a failure dump, even with long file paths on Windows. For example: don't upload the files with paths over 256 character, or shorten their folder names (this should be logged though).

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-851)

**Comment by Piedone** [comment]
https://github.com/Lombiq/UI-Testing-Toolbox/pull/362 fixes this too.
