### ISSUE TITLE
Latest tags aren't moving in a local clone (OSOE-910)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#389]
[Jira issue](https://lombiq.atlassian.net/browse/OSOE-910)

**Comment by BenedekFarkas** [comment]
Updated the title, because the tags are moving in the repo correctly, but not in a local clone when fetch/prune all is ran. I'm trying to determine which option causes them to move (to be in sync with origin), because Fetch All (in GitExtensions) is not enough: It's probably `Fetch All Tags`, but `Prune remote branches` and tags might affect it too (?).

**Comment by Piedone** [comment]
Yeah, this is some peculiarity with Git Extensions only.

**Comment by BenedekFarkas** [comment]
Workaround: Add a script with `git` as the command and `fetch --prune-tags --force` arguments for the `AfterFetch` event, like so:
![image](https://github.com/user-attachments/assets/13cfde3e-056a-44e9-bb3d-1ba8c12307ae)
