### ISSUE TITLE
Tag Version (this repo) fails due to branch protection rules (OSOE-912)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#396]
The last step named `Commit and Push Merge Target Changes` fails, because the `dev` branch is protected.

```
remote: error: GH006: Protected branch update failed for refs/heads/dev.        
remote: 
remote: - Changes must be made through the merge queue        
remote: 
remote: - Required status check "validate-gha-refs" is expected.        
To https://github.com/Lombiq/GitHub-Actions
 ! [remote rejected] dev -> dev (protected branch hook declined)
error: failed to push some refs to 'https://github.com/Lombiq/GitHub-Actions'
Error: Invalid status code: 1
```

1. Make the last two steps in the `tag-version` workflow skippable by configuration.
2. Add instructions to the readme on how to resolve it:
    - As an elevated user (with push access to `dev`):
      - Start a merge from the release branch to `dev`, but don't create a commit.
      - Revert all the file changes.
      - Merge the empty commit.
    - Otherwise:
      - Create a commit on the release branch that reverts all the file the changes (compared to `dev`).
      - Create a PR for the release branch and merge it.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-912)

**Comment by Piedone** [comment]
We can change the branch protection rule or something to allow just these. I think I have a solution, will follow up.
