### ISSUE TITLE
Setting "ui-test-parallelism" results in error (OSOE-183)

### ISSUE THREAD

**Issue by dministro** [Lombiq/GitHub-Actions#47]
When setting "ui-test-parallelism" to "1" in a GH workflow, the step fails with the error message "The term 'Set-XUnitMaxParallelThreads' is not recognized as...".

Example to reproduce: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/156/commits/087c32201464700ba8e066237098da4b3b380f39
Failed GH workflow: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/8178030883?check_suite_focus=true

**Comment by Piedone** [comment]
Did other values work?

**Comment by dministro** [comment]
I tryed only with `1`, but based on source code, any other value then `-1` results the same.
