### ISSUE TITLE
Change curl call to --fail-with-body (OSOE-382)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#53]
In the `create-jira-issues-for-community-activities` action, change `--fail` to `--fail-with-body`.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-382)

**Comment by BenedekFarkas** [comment]
Should be updated to use `Invoke-WebRequest` and without backticks instead: https://github.com/Lombiq/GitHub-Actions/pull/120#discussion_r1051649524

**Comment by Piedone** [comment]
This is not needed anymore, see https://github.com/Lombiq/GitHub-Actions/pull/120#discussion_r1052666046.
