### ISSUE TITLE
Migrate from deprecated set-output commands (OSOE-397)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#68]
The `Write-Output "::set-output name=my-output::$myOutput"`-style commands [are now deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). Follow the instructions in the announcement to migrate away from them.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-397)

**Comment by MZole** [comment]
I have updated our workflows and actions accordingly, but I think the majority of these warnings come from external GitHub actions, for example: `setup-dotnet`, `actions-label-merge-conflict`. As I have seen, the merge conflict workflow doesn’t have this migration yet, but the dotnet setup does. Should I update this action to the newest version? They have just updated the @actions/core package, but I don’t know if this has some cascading effect on us.

Also, is that possible to somehow test our `create-jira-issues` action in my issue branch? I have already changed the branches in the workflow imports to my issue branch. Maybe a solution is that If I add a `push:` to the `on:` property, but I don't want to create a jira issue, so just asking to make sure.

**Comment by Piedone** [comment]
For those actions where there is an update then yes, please update them to the latest version.

For those where there is no update, do two things:

- Open an issue in their repo about fixing this deprecation if there isn't one already.
- Link that issue where we use the action.

Yes, you can test `create-jira-issues` by temporarily changing the trigger. Feel free to do that, just please also temporarily change the project key to ADHOC so not OSOE issues are created (and then delete both the GitHub and Jira test issues).

**Comment by MZole** [comment]
So far I have gathered the following information:
- I have migrated all of our actions and tested the `create-jira-issues` action and now it only generates 1 warning instead of 8, and I will have to open an issue about this in [gajira-create](https://github.com/atlassian/gajira-create). (Also I can't delete my test issue on [jira](https://lombiq.atlassian.net/browse/ADHOC-251))
- There are already 2 issues open in the other 2 workflows which need to be migrated, in `test-reporting` and `label-merge-conflict`, what exactly do you want me to do? Comment on the issues and link our builds and warnings?

**Comment by Piedone** [comment]
OK then. I removed the Jira issue.

As I mentioned, please link the action issue where we use the action, so we know that this is a known problem and the author was notified.

**Comment by MZole** [comment]
I have done everything you requested, will this issue be blocked until the external workflows do the migration or I can put this to done since some of the repositories seem pretty abandoned and it will be a separate issue when they take action?

**Comment by Piedone** [comment]
Wait until a week passes since the newest of these issues were opened. If still no reply from maintainers, then you're done, yes.
