### ISSUE TITLE
Fix test reports sometimes showing up under different workflows, or not at all (OSOE-408)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#73]
This most possibly needs to be fixed in `phoenix-actions/test-reporting`. See details here: https://github.com/phoenix-actions/test-reporting/issues/25

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-408)

**Comment by Piedone** [comment]
It turns out that this is due to there being no way to connect the run with a check suite. See https://github.com/orgs/community/discussions/24616. This is what's mentioned in the action's Readme [here](https://github.com/phoenix-actions/test-reporting#:~:text=Check%20Runs%20are%20created%20for%20specific%20commit%20SHA). [This PR](https://github.com/phoenix-actions/test-reporting/pull/21) adds a workaround.

**Comment by Piedone** [comment]
I'll check out the PR and see if it's a good stopgap, at least.

Probably `(github.event.pull_request == '' || github.event.pull_request.head.repo.fork == false)` can be remove too if we use the workflow summary, or does it still need write access?

**Comment by dministro** [comment]
https://github.com/phoenix-actions/test-reporting/pull/21 get merged, great.
I worried a bit about using an issue branch.
