### ISSUE TITLE
Very slow Tests step in Build and Test GHA workflow despite fast tests (OSOE-409)

### ISSUE THREAD

**Issue by 0liver** [Lombiq/GitHub-Actions#76]
The **Tests** step now takes around [7m](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3297727231/jobs/5438909130) to [8m](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3299076917/jobs/5442414689) on the 8-core-Windows runner across different branches.

### Problem

But on OSOE-84, it takes [22m](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3292870136/jobs/5428740126)!

Turns out, **14 minutes** of the 22 are spent looking for _xunit.runner.json_ files:

![image](https://user-images.githubusercontent.com/164360/197268271-fd6a5f3d-d619-468c-a1a5-60a2f4e52fc2.png)

That because of a very inefficient way to search for them:

```pwsh
Get-ChildItem "*/**/xunit.runner.json" -Recurse
```

### Solution

Let's make searching for those files fast - and save ~some real money~ the planet.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-409)

**Comment by 0liver** [comment]
### Findings

```pwsh
Measure-Command { Get-ChildItem xunit.runner.json -recurse | write-host }
```
`TotalSeconds      : 146,9143848`

```pwsh
Measure-Command { Get-ChildItem -recurse -Filter xunit.runner.json -FollowSymlink -WarningAction Ignore }
```
`TotalSeconds      : 2,5238978`

**Comment by 0liver** [comment]
## 7:03 on Windows! 🎉
### (instead of 22:19)

https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3300301716/jobs/5444646780

**Comment by sarahelsaig** [comment]
I tend to avoid `Get-ChildItem -Recurse`. It's insultingly slow, especially compared to GNU `find`. (I wonder if we could just use that in GHA even in `pwsh`? It's surely installed along with bash even on the windows VM.)

Also check out the function I made in PowerShell-Analyzer to speed things up and avoid entering irrelevant directories [here](https://github.com/Lombiq/PowerShell-Analyzers/blob/cc98664e5282b9295ddd0a0770a9db4c83a8f6ab/Lombiq.Analyzers.PowerShell/Invoke-Analyzer.ps1#L8-L33).

**Comment by Piedone** [comment]
Nice find!

**Comment by 0liver** [comment]
Thanks, @DAud-IcI!

I've tried your custom function with the following result:

```pwsh
measure-command { Find-Recursively -IncludeFile "xunit.runner.json" -ExcludeDirectory node_modules }
```
`TotalSeconds      : 13,587331`

Compare this to:

```pwsh
Measure-Command { Get-ChildItem -recurse -Filter xunit.runner.json -FollowSymlink -WarningAction Ignore }
```
`TotalSeconds      : 2,5238978`

I think, in the case at hand, the `-Filter` parameter is really the booster, and I doubt we can get **much** faster than that. I'd avoid complicating this fix any further by moving to GNU `find`.

**Comment by sarahelsaig** [comment]
I was afraid of that, but thanks for measuring anyways. My function is really beneficial when you have some deep populated directories, especially _node_modules_, but I think those don't yet exist at this point of the workflow.

**Comment by 0liver** [comment]
I've done the measurement on my local machine, where the _node_modules_ folders do exist.

My numbers don't compare to the example numbers in your script file, only to each other. And there, `Get-ChildItem` with `-Filter` is clearly faster.

**Comment by sarahelsaig** [comment]
Good to know.
