### ISSUE TITLE
Automatically add Jira issue key prefix and link to pull requests (OSOE-425)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#86]
- In the `validate-pull-request` workflow, implement automation to prefix a newly opened PR's title with the corresponding Jira issue key, as well as add a link to the issue into the PR's description, if these are not there already. The issue key can be determined from the branch name.
- Don't do anything if the branch name doesn't match an issue key pattern (like for community contributions).
- In all OSOCE submodules, change `verify-submodule-pull-request` workflows to `validate-pull-request`. These should include a call to a new, `validate-submodule-pull-request` reusable workflow, that runs both the submodule verification and the issue key insertion. The `validate-this-pull-request` workflow should be adapated.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-425)

**Comment by Luko6** [comment]
There is some black magic that already puts the link into the issue key in the description, is this action intended to replace that too? If out of habit someone provides the key in the description, what should happen?

**Comment by Piedone** [comment]
> There is some black magic that already puts the link into the issue key in the description, is this action intended to replace that too?

For this purpose, yes. That's a GitHub feature the replaces issue keys anywhere with links pointing to issues. That'll remain, but this feature should insert a link nevertheless and not rely on the automatic replacement.

> If out of habit someone provides the key in the description, what should happen?

If the issue key is present in the PR title or in the description then this feature should just leave them and don't duplicate (note that it can be that the PR title has an issue key but the description doesn't and vice versa; the missing issue key should still be added).

**Comment by Piedone** [comment]
Oh yeah, this should work together with submodule verification, so the latter only runs once the PR got an issue prefix, if available.

**Comment by Luko6** [comment]
1. What happens to the `check-merge-conflict` workflow? That's currently the `validate-pull-request` workflow itself, should it be included in the new one so: Prefix, Parent, Merge Conflict would be in it.
2. What happens in OSOCE? Currently the only the Merge conflict check runs there. Should that be expanded with Prefix checking? Because reusing the new workflow doesn't make sense since checking for Parent PR there doesn't make sense.

**Comment by Piedone** [comment]
1. Add it as first step before the `check-merge-conflict` one. Note that unlike `check-merge-conflict`, this shouldn't run on any `push`.
2. If you mean the OSOE superproject then the same (it doesn't use submodule verification). For submodules, see the third point in the issue description.

**Comment by Luko6** [comment]
There is a problem, the `Veryify Submodule Pull Request` action/step fails the first time when no issue key is provided. This is because it uses the original PR title. I looked into it and this new workflow makes the first two step in `Verify...` obsolete, since it first checks if the title is "valid". The parent check would run into the same problem.

I think it would be the best if that workflow got removed and the functionality merged into this one.

What do you think?

**Comment by Piedone** [comment]
As elaborated in the third point of the issue, yes, we won't need a separate `verify-submodule-pull-request` workflow. However, the `verify-submodule-pull-request` **action** still needs to be called from the new workflow, because its point is not about validating the PR title format, but checking the existence of a superproject PR. This functionality should remain but the action indeed needs to be modified not to fail when the PR title doesn't contain an issue key, but then just ignore it.

**Comment by Luko6** [comment]
I'm talking about merging the two actions, moving "Superproject PR existence check" to the "Prefix PR" action, since it already knows about the new title, and can just as easily perform the check.

**Comment by Piedone** [comment]
Keep in mind that we need PR title prefixing in standalone repos and superprojects (like OSOCE) too, not just submodules.

**Comment by Luko6** [comment]
During the review process you requested to change how I get the title, body and PR number. However in the current version, this only works if the workflow was triggered by a `pull_request` and does not work on `push` which is used by the non-submodule version of the validation workflow.

The easiest solution would be separating this action from the `Check Merge Conflict` action (which is the one utilizing `push`)

Can you confirm please?

**Comment by Piedone** [comment]
You can check for `github.event.pull_request` being empty; if it is, then it's not a PR, and you can leave out the PR-specific things (`create-jira-issues-for-community-activities` does this too).

Putting merge conflict checks into their separate workflow would definitely be cleaner. However, there's a practical issue with running tiny pieces of automation with GHA: Every workflow run provisions a new VM, and if done in private repos, is billed by the minute. So, it would be wasteful to split these (we can actually have a lot more checks in this workflow in the future even just to reach a minute of runtime).

**Comment by Luko6** [comment]
I see, I'll check it out, thanks!
